### ISSUE TITLE
an optimization

### ISSUE THREAD

**Issue by syfoud** [StareAbyss/FoodsVsMouses_AutoAssistant#1]
![屏幕截图 2023-12-28 194339](https://github.com/StareAbyss/FoodsVsMouses_AutoAssistant/assets/87754314/748f08a1-ec2f-466a-90be-5453ef723281)
Please resolve multiple server ventilation issues

**Comment by StareAbyss** [comment]
This problem has been solved in version 0.8.1. look at below~

* 更新了 卡死判断机制, 根据 创建房间/进行战斗 的不同情况, 会一定程度智能判断卡死程度, 以进行 跳过本次作战 或 重启再进行本次作战
  * 该机制更新后, 可以以两个账号中火山遗迹次数更多的号的次数, 来进行ui中次数的填写, 只要能创房间, 无法开始对局时(30s等待), 会智能判断跳过
  * 该机制更新后, 当邀请动作连续失败5次, 会直接reload游戏再尝试邀请, 大幅降低卡死的可能性
