### ISSUE TITLE
360游戏大厅隐藏工具栏后无法工作

### ISSUE THREAD

**Issue by mamaruo** [StareAbyss/FoodsVsMouses_AutoAssistant#4]
![image](https://github.com/StareAbyss/FoodsVsMouses_AutoAssistant/assets/37480168/aca35be7-cf4d-4454-b38b-4647f2b31ce4)

表现为无法刷新游戏。

**Comment by StareAbyss** [comment]
这是正常情况，因为依赖工具栏的刷新按钮进行刷新，在简易文档中有专门注明不能隐藏工具栏
